### ISSUE TITLE
Doesn't handle merging of hashes

### ISSUE THREAD

**Issue by hderms** [stephank/yaml.node#4]
the following yaml will not have &defaults merged in to the various hashes. This should happen.

``` yaml
defaults: &defaults
  input_location: common_input
  output_location: dev_location
  mail:
    sender_name: sender
    smtp_server: your_server
    login: your_login
    password: top_secret
development:
  <<: *defaults
production:
  <<: *defaults
  output_location: prod_location
```
